### PR TITLE
update README

### PR DESCRIPTION
**Pull request by ninariccimarie**
ref: https://github.com/filoxo/solid-state-react/issues/1

### CODE REVIEW

**Comment by ninariccimarie** [comment]
hello @filoxo please review

**Comment by ninariccimarie** [comment]
hi @filoxo thanks for the review! sure thing, I just updated the PR. Please review

**Comment by jrdevforlife** [comment]
You don't need `yarn install`, it's simply `yarn`

**Comment by filoxo** [comment]
I'm going to prefer `yarn install` as its more explicit as to what will happen, just for ease of use for beginners. Users with more experience with yarn will know to do the same thing in other ways.

**Comment by filoxo** [comment]
Thanks for your help @ninariccimarie!

**Pull request merged**
